# Generated by Django 5.2.16 on 2026-09-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_onetimecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Account verification'), ('reset', 'Password reset')], default='verify', max_length=10),
        ),
    ]
