# Generated by Django 5.2.16 on 2026-09-25 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_terms_accepted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20)),
                ('rating', models.CharField(choices=[('bad', 'Bad'), ('fine', 'Fine'), ('good', 'Good')], max_length=10)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True)),
                ('page', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
