# Generated by Django 5.2.16 on 2026-10-01 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sitefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updates_opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('teaser', models.CharField(help_text='One or two sentences shown in the email.', max_length=220)),
                ('points', models.TextField(help_text='One point per line.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='users.siteupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('update', 'user')},
            },
        ),
    ]
