# Generated by Django 5.2.16 on 2026-10-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_site_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthThrottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=190, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='onetimecode',
            name='target_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Account verification'), ('reset', 'Password reset'), ('newemail', 'New login email'), ('contact', 'Contact email')], default='verify', max_length=10),
        ),
    ]
