# Generated by Django 5.2.16 on 2026-10-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_email_verification_and_throttle'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteupdate',
            name='kind',
            field=models.CharField(choices=[('news', "What's new (new features)"), ('encouragement', 'A word of encouragement (warm gold look, with a verse)')], default='news', max_length=20),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='verse',
            field=models.CharField(blank=True, help_text='Optional. Shown at the top, for example a Bible verse.', max_length=220),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='verse_ref',
            field=models.CharField(blank=True, help_text='Where the verse is from, for example Proverbs 27:17.', max_length=60),
        ),
    ]
