# Generated by Django 6.0.6 on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
