# Generated by Django 5.2.16 on 2026-08-05 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0006_scout_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='verification_document',
            field=models.FileField(upload_to='scout_verification_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
