# Generated by Django 5.2.16 on 2026-09-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0007_alter_scout_verification_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutvideofeedback',
            name='player_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoutvideofeedback',
            name='scout_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scoutvideofeedback',
            name='scout_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
