# Generated by Django 5.2.16 on 2026-09-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_remove_playerprofile_previous_club_duration_and_more'),
        ('scouts', '0008_scoutvideofeedback_player_reply_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutPlayerShortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', help_text='Your private notes about this player.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='players.playerprofile')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('scout', 'profile'), name='unique_scout_player_shortlist')],
            },
        ),
    ]
