# Generated by Django 5.2.16 on 2026-10-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0009_scoutplayershortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='scouts_for',
            field=models.CharField(choices=[('both', 'Stars and Starlets'), ('stars', "Stars (men's football)"), ('starlets', "Starlets (women's football)")], default='both', max_length=10),
        ),
    ]
