# Generated by Django 5.2.16 on 2026-10-03 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_stars_and_starlets'),
        ('scouts', '0010_stars_and_starlets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FairPlayAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualities', models.CharField(help_text='Comma-separated quality keys.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_play_awards', to='players.playerprofile')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_play_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('scout', 'profile'), name='unique_fair_play_per_scout')],
            },
        ),
    ]
