# Generated by Django 5.2.16 on 2026-10-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0012_photo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutvideofeedback',
            name='scout_seen_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
