# Generated by Django 6.0.6 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunity_posters/'),
        ),
    ]
