# Generated by Django 5.2.16 on 2026-10-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_opportunity_max_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('open', 'Open to all'), ('stars', "Stars (men's football)"), ('starlets', "Starlets (women's football)")], default='open', max_length=10),
        ),
    ]
