# Generated by Django 5.2.16 on 2026-10-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_stars_and_starlets'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('transport', 'Transport or fare was a problem'), ('school_work', 'School, exams or work'), ('injury', 'Injured or unwell'), ('family', 'Family reasons'), ('cancelled', 'The event was cancelled or moved'), ('late_news', 'I saw the news too late'), ('other', 'Other')], db_default='', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='attendance_answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='attendance_note',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='attended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
