# Generated by Django 5.2.16 on 2026-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_playerprofile_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='previous_club',
            field=models.CharField(blank=True, help_text='Most recent previous club or academy.', max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='previous_club_duration',
            field=models.CharField(blank=True, help_text='Duration at previous club, e.g. 7 months or 2 years.', max_length=50),
        ),
    ]
