# Generated by Django 5.2.16 on 2026-09-18 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_playerprofile_previous_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playervideo',
            name='category',
            field=models.CharField(choices=[('highlights', 'Highlights'), ('match', 'Match Footage'), ('training', 'Training'), ('skills', 'Skills Showcase')], default='highlights', help_text='Helps scouts quickly understand what this clip shows.', max_length=20),
        ),
        migrations.AddField(
            model_name='playervideo',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: add context such as the match, opponent, or what to look out for.'),
        ),
        migrations.CreateModel(
            name='ClubExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=150)),
                ('duration', models.CharField(blank=True, help_text='Example: 2019 - 2021, or 8 months.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Your role, achievements, and highlights at this club.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_experiences', to='players.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
