# Generated by Django 5.2.16 on 2026-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_playervideo_category_playervideo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='previous_club_duration',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='previous_club_end_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year you left the previous club, e.g. 2021.', null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='previous_club_start_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year you joined the previous club, e.g. 2019.', null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='football_experience',
            field=models.TextField(blank=True, help_text='Briefly describe your achievements and highlights at your previous club.'),
        ),
        migrations.DeleteModel(
            name='ClubExperience',
        ),
    ]
