# Generated by Django 5.2.16 on 2026-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_remove_playerprofile_previous_club_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Used to keep your age accurate automatically.', null=True),
        ),
    ]
