# Generated by Django 5.2.16 on 2026-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_playerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='guardian_consent_at',
            field=models.DateTimeField(blank=True, help_text='When a parent/guardian consent was confirmed for a player under 18.', null=True),
        ),
    ]
