# Generated by Django 5.2.16 on 2026-09-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_playerprofile_guardian_consent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='guardian_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='guardian_declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='guardian_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
