# Generated by Django 5.2.16 on 2026-10-02 10:56

from django.db import migrations, models
from django.utils import timezone


def verify_matching_contact_emails(apps, schema_editor):
    # A contact email that is the same as the (already verified) login email counts as verified.
    PlayerProfile = apps.get_model('players', 'PlayerProfile')
    for profile in PlayerProfile.objects.exclude(contact_email__isnull=True).exclude(contact_email='').select_related('user'):
        if profile.contact_email.strip().lower() == (profile.user.email or '').lower():
            profile.contact_email_verified_at = timezone.now()
            profile.save(update_fields=['contact_email_verified_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_guardian_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='contact_email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(verify_matching_contact_emails, migrations.RunPython.noop),
    ]
