# Generated by Django 5.2.16 on 2026-10-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_email_verification_and_throttle'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('stars', "Stars (men's football)"), ('starlets', "Starlets (women's football)")], default='', max_length=10),
        ),
    ]
