# Generated by Django 5.2.16 on 2026-10-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_stars_and_starlets'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='photo_position',
            field=models.CharField(blank=True, default='50% 30%', max_length=20),
        ),
    ]
